language: java

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

script:
  - docker-compose build

deploy:
  provider: heroku
  api_key:
    secure: gbjolG6tYHd5/2WhwsFZUivXM7ZkBehfKWe3VTsxPdz/CF6Uo9GEWE7ZzMQfXtNJhLNc14UBNmSDUMRxbaHWRCSyE4adnCm/jyU2JEri4blxyMgMBi/5DLozVzbMqkTzdrPIyissK9aOYPNoR835esZYCfnTyxWSExjDVQdh+l0siXWqvArxp0ra4D+M/zJXEuFwWFPyZfwHmOqkiuyIl0d9eJV3kxJCLigiv/NOYLAPSfOGSFNDrFZCc3m2hckztNTt5aFd6U3vvsxHDyKCB2ljuieITbR4vOBVOHcikGuktmeB4+uE5Y30FhAF5X4QEskxzjkcHXojTKrvoGtD3oBEL9gqeaej1ZO2I1ijHV2eJ3SLUqk1RcEYvObboG7Nl0Xgt4lvia9x+bdUP9fw19ECgJ4hOX/6SOZvu+Us8nEQg09i4z/UX/7+oNXX21kEOEiXykh97rvzzfS7sK3sQFGvhv7WrjceWuYL1R0qmpruETA6OAVebi2KcuOhJ3jGKcO9yg4Uqfv2ggG2dsG86RvEDyIKrkv8Q66Fc/0CyBoUlw7ZLpQPnhCTWPIZ6sUGterTGi4elNMpgrDNZweYzlBZXO8lVZq3ysAm/Jg8HQRgNALDwxOIb7NbWUWweHEW1UkYl4Aii009YUtHF92/s0psqhkTkNq0S3hKF+wMS8A=
