version: "3"
services:
  awards-service:
    build: ./awards-service
  awards-frontend:
    build: ./awards-frontend
    ports:
      - "4200:80"
  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
