version: "3"

services:
  awards-service:
    build: ./awards-service
    ports:
      - "5001:5001"
  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
  awards-frontend:
    build: ./awards-frontend
    ports:
      - "4200:80"
