server:
  port: 5000

spring:
  application:
    name: api-gateway

# Uncomment to enable debug logging
#logging:
#  level:
#    reactor:
#      netty: INFO
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE
