server:
  port: 5001

---

spring:
  profiles: default, test, local
  data:
    mongodb:
      host: localhost
      port: 0
      database:
        'awards'

---

spring:
  profiles: docker
  data:
    mongodb:
      host: localhost
      port: 0
      database:
        'awards'
